name: Autopsy

on: [push, pull_request]

env:
  AUTOPSY_DOCKER_USERNAME:  ${{ github.actor }}
  AUTOPSY_DOCKER_PASSWORD:  ${{ github.token }}

  AUTOPSY_DOCKER_IMAGE_TAG: ghcr.io/${{ github.repository }}

jobs:
  autopsy:
    name: Autopsy
    runs-on: ubuntu-latest
    
    steps:
      - name: Performing Autopsy
        uses: achillesrasquinha/autopsy@develop